cmake_minimum_required (VERSION 2.8)

get_filename_component (STFCOMMON_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)

set (STFCOMMON_FOUND TRUE)
set (STFCOMMON_INCLUDE_DIRS ${STFCOMMON_PREFIX}/include/)
set (STFCOMMON_DEFINITIONS)

if (DEFINED STFCOMMON_NDEBUG)
    set(STFCOMMON_DEFINES ${STFCOMMON_DEFINITIONS}
        -DLOG_NDEBUG=${STFCOMMON_NDEBUG})
    #message("STFCOMMON_NDEBUG=${STFCOMMON_NDEBUG}")
endif()
if (DEFINED STFCOMMON_NPERF)
    set(STFCOMMON_DEFINITIONS ${STFCOMMON_DEFINITIONS}
        -DLOG_NPERF=${STFCOMMON_NPERF})
    #message("STFCOMMON_NPERF=${STFCOMMON_NPERF}")
endif()

set (STFCOMMON_NAME StfCommon)
set (STFCOMMON_LIBRARIES ${STFCOMMON_NAME})

set (STFCOMMON_BUILD_KO ${STFCOMMON_PREFIX}/StfCommon_kernel.cmake)
