cmake_minimum_required (VERSION 2.8)

get_filename_component (MEDIACTRLLIB_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)

set (MEDIACTRLLIB_FOUND TRUE)
set (MEDIACTRLLIB_INCLUDE_DIRS ${MEDIACTRLLIB_PREFIX}/include)
set (MEDIACTRLLIB_DOXYGEN_SRC ${MEDIACTRLLIB_PREFIX}/src)
set (MEDIACTRLLIB_DEFINITIONS)
set (MEDIACTRLLIB_NAME media-ctrl)
set (MEDIACTRLLIB_LIBRARIES ${MEDIACTRLLIB_NAME})
